### ISSUE TITLE
add a short lab?

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/reading-ios-things-nsstring-can-do#6]
@markedwardmurray maybe add a short lab in which we declare some variable, manipulate some strings? There are a lot of readings here and I always feel like I don't understand something till I try it out myself.

**Comment by markedwardmurray** [comment]
yeah, i agree. it definitely needs *something*, whether that's short labs or quizzes in Learn. All of the existing labs weren't any simpler than arrays, so it's definitely a hole right now.

**Comment by markedwardmurray** [comment]
created a code along objc-parrot to address this
