### ISSUE TITLE
Xcode crashes when trying to open the .xcodeproj file

### ISSUE THREAD

**Issue by jineshshah36** [learn-co-curriculum/reading-ios-things-nsstring-can-do#9]

**Comment by markedwardmurray** [comment]
this is reading that has no companion lab. This is an Xcode 7 compatability problem, please Ask A Question in Learn instead of raising an issues for this. Which lab are you having trouble with?

**Comment by jineshshah36** [comment]
The parrot lab. It crashes xcode on startup. I skipped it but I thought you guys should know. Sorry, I raised the issue in the wrong place.

**Comment by markedwardmurray** [comment]
there's a bug in Xcode 7 that causes this lab crash (and many others). We actually fixed it two weeks but the changes didn't get redeployed to the 001 repo that your fork is on. I let engineering know about it and i'll let you know when the fix is ready.

**Comment by markedwardmurray** [comment]
i just opened a PR on your fork of objc-parrot. please reach out if you have problems with other labs.
